fix: add Vega-Lite as a dependency
uwdata/mosaic pull request #402
Opened 2024-05-23 17:55 UTC by kzhang31415

Vega-Lite isn't installed despite being listed as a peer dependency of Vega-embed, installing Vega-lite as a dependency works as a fix for now.

2024-05-23 17:57 UTC, domoritz requested changes

2024-05-23 17:57 UTC, domoritz commented on package.json
> +    "vega-lite": "^5.18.1"
Please add the dependency to the specific package that needs it.

2024-05-23 18:33 UTC, kzhang31415 commented
I've just moved the dependency to the vega-embed package since that's the one that needs it.

2024-05-23 20:27 UTC, domoritz commented
I don't see the change to any package.json file.

2024-05-23 23:51 UTC, kzhang31415 commented
Sorry, it looks like my changes didn't pass some of the checks because I hadn't properly uninstalled my dependencies to test them.

2024-05-24 02:03 UTC, domoritz commented
There are unrelated changes now. Please check your changes. 

I'll make this pull request as draft until you are confident that it's ready.

2024-05-24 02:26 UTC, kzhang31415 commented
Is there a way to test the checks on my local computer before sending it for approval? "npm ci" worked on my side but failed here for some reason.

2024-05-24 03:10 UTC, domoritz commented
Npm run test

2024-05-24 22:33 UTC, closed without merging

2024-05-24 22:37 UTC, kzhang31415 commented
Issue is gone now, seems to be fixed with the recent commit from sheer