Asynchronous Querying Implemented
uwdata/mosaic pull request #438
Opened 2024-06-20 17:13 UTC by kzhang31415

Still not sure whether the queries come back in the right order, but queries are now sent without waiting for the previous queries to return. Please let me know if any changes need to be made to the code.

2024-06-21 01:12 UTC, kzhang31415 commented
Pull request has been cleaned up by the most recent commit, changes in all other files besides QueryManager.js have been reverted

2024-06-24 17:03 UTC, jheer commented
Thanks! A few quick notes:

- 4/5 files in this PR have unnecessary changes. Only QueryManager needs to be edited.
- Main TODOs for issuing multiple queries in parallel is (1) to ensure correctness of the results and (2) measure to what degree, if any, doing so improves performance. So we would want to get tests and possible some performance measures in place before we merge a PR that eliminates query serialization.

2024-06-24 20:57 UTC, domoritz requested changes
Thanks for the pull request. Please make sure only necessary changes are included in the future. 

Please add an explanation for the changes you made in the pull request description. 

Also, we will need to evaluate the actual performance improvements and also make sure that the order or queries is preserved. I think a combination of unit tests and a semi-format proof would be best to show that.

2024-06-24 20:57 UTC, domoritz commented on package-lock.json
Please undo this change.

2024-06-24 20:57 UTC, domoritz commented on package-lock.json
> +}
Please undo this change.

2024-06-24 20:57 UTC, domoritz commented on package.json
> +}
Please undo this change.

2024-06-24 20:57 UTC, domoritz commented on packages/core/src/QueryManager.js
> +    /* */
```suggestion
```

2024-06-24 20:57 UTC, domoritz commented on packages/core/src/util/convert-arrow.js
> +}
Please undo this change.

2024-06-24 20:57 UTC, domoritz commented on packages/core/src/util/selection-types.ts
> +}
Please undo this change.

2024-06-24 20:57 UTC, domoritz commented on packages/core/src/QueryManager.js
> +    /* */
Please don't comment out code in a pull request but remove it so we can see the diff.

2024-07-11 19:01 UTC, kzhang31415 commented
[Query_Parallelization_Writeup.pdf](https://github.com/user-attachments/files/16182401/Query_Parallelization_Writeup.pdf)
Here is a writeup including a proof of performance increase due to changes in this pull request, some benchmarks on the performance gains, and pseudocode of the new and old code. I've also just added unit tests in the coordinator-test.js file. I'm still unable to remove package-lock.json from the changed files for some reason, despite there being no changes in that file.

2024-07-15 17:12 UTC, domoritz requested changes

2024-07-15 17:12 UTC, domoritz commented on packages/core/test/coordinator-test.js
> +import { resolve } from 'node:path';
bad imports

2024-07-15 17:12 UTC, domoritz commented on packages/core/src/QueryManager.js
> +          this._logger.debug(`Cache`);
please undo

2024-07-15 17:12 UTC, domoritz commented on packages/core/src/QueryManager.js
> +          results[i].fulfill(data);
I don't think this correctly sorts the results yet, no? The request is fulfilled in the order of the `then` in line 96.

2024-07-15 17:12 UTC, domoritz commented on packages/core/test/coordinator-test.js
> +  it('has accessible singleton', async () => {
```suggestion
  it('has accessible singleton', () => {
```

2024-07-15 17:12 UTC, domoritz commented on packages/core/test/coordinator-test.js
> +        let result = new Promise((resolve, reject) => setTimeout(() => resolve(id), 200*(10-id)));
Let's not use timeout in tests because it slows down the tests. Instead figure out a way to resolve the promises out of order.

2024-07-22 20:09 UTC, kzhang31415 commented
Updated writeup with proof of correct
[Query_Parallelization_Writeup.pdf](https://github.com/user-attachments/files/16339287/Query_Parallelization_Writeup.pdf)
 results ordering

2024-08-02 23:12 UTC, domoritz commented
This still doesn't seem to be correct. 

with this test

```
async function wait() {
  return new Promise(setTimeout);
}

describe("coordinator", () => {
  it("query results returned in correct order", async () => {
    const promises = [];

    const connector = {
      async query() {
        const promise = new QueryResult();
        promises.push(promise);
        return promise;
      },
    };

    const coord = new Coordinator(connector);

    const r0 = coord.query();
    const r1 = coord.query();
    const r2 = coord.query();
    const r3 = coord.query();

    // queries have not been sent yet
    assert.equal(promises.length, 0);

    await wait();

    // all queries should have been sent to the connector
    assert.equal(promises.length, 4);

    // resolve promises in reverse order
    promises.at(-1).fulfill();
    assert.equal(r0.pending, true);

    promises.at(-2).fulfill();
    assert.equal(r1.pending, true);

    promises.at(-3).fulfill();
    assert.equal(r2.pending, true);

    // promises are only fulfilled after the last request to the coordinator resolves
    promises.at(-4).fulfill();
    assert.equal(r0.pending, false);
    assert.equal(r1.pending, false);
    assert.equal(r2.pending, false);
    assert.equal(r3.pending, false);
  });
});

```

and changing query result to 

```
/**
 * A query result Promise that can allows external callers
 * to resolve or reject the Promise.
 */
export class QueryResult extends Promise {
  /**
   * Create a new query result Promise.
   */
  constructor() {
    let resolve;
    let reject;
    super((r, e) => {
      resolve = r;
      reject = e;
    });
    this._resolve = resolve;
    this._reject = reject;
    this._pending = true;
  }

  /**
   * Resolve the result Promise with the provided value.
   * @param {*} value The result value.
   * @returns {this}
   */
  fulfill(value) {
    this._pending = false;
    this._resolve(value);
    return this;
  }

  /**
   * Rejects the result Promise with the provided error.
   * @param {*} error The error value.
   * @returns {this}
   */
  reject(error) {
    this._pending = false;
    this._reject(error);
    return this;
  }

  /**
   * Whether this promise is still pending.
   * @returns {boolean}
   */
  get pending() {
    return this._pending;
  }
}

// necessary to make Promise subclass act like a Promise
QueryResult.prototype.constructor = Promise;
```

it looks like the responses are resolved before all the requests return from the connector

2024-08-05 03:14 UTC, domoritz commented
I think this needs a bit more work to be correct but also address some missing features.

* support canceling queries
* support limiting the number of queries sent
* support caching and not sending the same query multiple times (while also supporting canceling)

I'm taking a stab at another approach in a separate branch and will share what I'm learning.

2024-08-14 05:48 UTC, domoritz commented
Superseded by #475.

2024-08-14 05:48 UTC, closed without merging