ts-expect-error on import in selection-types.ts
uwdata/mosaic pull request #544
Opened 2024-10-02 17:55 UTC by jordanhboxer

This needs to be added otherwise I have to disable `noImplicitAny` in my tsconfig.json which can hide other errors.

2024-10-02 18:13 UTC, kwonoh commented
I get the below error from a typescript project with `"noImplicitAny": true` while this repo has `"noImplicitAny": false`. 

```
[TypeScript] Could not find a declaration file for module '../MosaicClient.js'. '<path>/@uwdata/mosaic-core/src/MosaicClient.js' implicitly has an 'any' type.
<path>/@uwdata/mosaic-core/src/util/selection-types.ts:2:30
    1 | import { SQLExpression } from '@uwdata/mosaic-sql';
  > 2 | import { MosaicClient } from '../MosaicClient.js';
      |                              ^^^^^^^^^^^^^^^^^^^^
    3 |
    4 | /**
    5 |  * Selection clause metadata to guide possible query optimizations.
 ```

Adding `// @ts-ignore` resolve the above issue. 

However, if `selection-types.ts` will only contain type definitions, I think it should be named as `selection-types.d.ts` so the library users can use [`skipLibCheck`](https://www.typescriptlang.org/tsconfig/#skipLibCheck) for addressing this kind of issue.

2024-10-02 19:36 UTC, domoritz requested changes
Can you enable `skipLibCheck` in your config? Wouldn't that ignore type errors in the library? 

If we want to make a change here, I would suggest that we enable `noImplicitAny` to check everything and avoid potential regressions and instead of ts-ignore, should we add the missing declarations?

2024-10-02 19:52 UTC, domoritz commented
I see. I'm okay with moving to .d.ts files for everything but iirc there was some reason @jheer used ts files. 

Id love to have a setup that lets is gradually transition to ts. If you could make a proposal that would be awesome. 

Happy to merge this pull request if it's a stopgap but you would probably need a release, no?

2024-10-02 20:09 UTC, domoritz commented
If you can, go ahead and try.

2024-10-02 20:28 UTC, kwonoh commented
Changing `selection-types.ts` to `selection-types.d.ts` seems to work locally. I didn't see any errors from build/lint/test/docs:build. Waiting for the repo's workflow to kick in.

2024-10-02 20:38 UTC, domoritz commented
Support supportive of going ts but we want to make sure it's done in a way where we don't need to re-compile a sub-project to get the updates in another. Ideally, we figure out some way to do gradual transitions, that would be best and then send follow up PRs to change individual models. 

Related: https://github.com/uwdata/mosaic/issues/312

2024-10-02 22:01 UTC, jordanhboxer commented
@jheer That sounds like the ideal solution given that that will produce the correct output in the built package rather than using a declaration file in the source code. 

To give you some more context, our build pipeline runs `tsc` on all `.ts` files and since it hasn't been compiled to a declaration file we can't ignore it `skipLibCheck`. Setting `"noImplicitAny": false` is not ideal for us either as that will hide potential issues.

2024-10-02 22:08 UTC, domoritz commented
Like this https://github.com/uwdata/mosaic/pull/545?

2024-10-02 22:12 UTC, jordanhboxer commented
I believe so!

2024-10-03 00:15 UTC, domoritz commented
Should be fixed by https://github.com/uwdata/mosaic/pull/545.

2024-10-03 00:15 UTC, closed without merging